---
- name: Set path.data in logstash.yml
  lineinfile:
    path: /etc/logstash/logstash.yml
    regexp: '^#?\s?path.data:.*$'
    line: 'path.data: /var/lib/logstash'

- name: Set path.config in logstash.yml
  lineinfile:
    path: /etc/logstash/logstash.yml
    regexp: '^#?\s?path.config:.*$'
    line: 'path.config: /etc/logstash/conf.d'

- name: Set path.logs in logstash.yml
  lineinfile:
    path: /etc/logstash/logstash.yml
    regexp: '^#?\s?path.logs:.*$'
    line: 'path.logs: /var/log/logstash'