---
- name: Installing Logstash
  apt: name=logstash

- name: Configure logstash to receive nginx filebeat logs
  include: configure_logstash_for_nginx_logs.yml

- name: Enabling and starting logstash as a systemd service
  systemd:
    enabled: yes
    name: logstash
    daemon_reload: yes
    state: restarted
