---
- name: Configuring ssl certificates
  become: yes
  become_method: sudo
  include: configure_ssl.yml
  
- name: Install elasticsearch
  become: yes
  become_method: sudo
  include: install_elasticsearch.yml

- name: Install kibana
  become: yes
  become_method: sudo
  include: install_kibana.yml

- name: Install logstash
  become: yes
  become_method: sudo
  include: install_logstash.yml
