---
- name: Configuring ssl certificates
  become: yes
  become_method: sudo
  include: configure_ssl.yml

- name: Install yq for editing yaml
  become: yes
  become_method: sudo
  include: install_yq.yml

- name: Install elasticsearch
  become: yes
  become_method: sudo
  include: install_elasticsearch.yml

- name: Install logstash
  become: yes
  become_method: sudo
  include: install_logstash.yml

- name: Install kibana
  become: yes
  become_method: sudo
  include: install_kibana.yml

- name: Setup nginx for kibana
  become: yes
  become_method: sudo
  include: setup_nginx_for_kibana.yml

- name: Setup ElasticAPM
  become: yes
  become_method: sudo
  include: setup_elastic_apm.yml
