- hosts: elk_server
  vars:
    nginx_access_log_pattern: '%{IPORHOST:remote_addr} - %{USERNAME:remote_user} \[%{HTTPDATE:timestamp}\]%{GREEDYDATA:extra_data}'
  tasks:
    - name: Installing ELK stack
      include: main.yml