---
- name: Install APM Server
  apt: name=apm-server

- name: Configure APM server to start automatically at boot
  command: update-rc.d apm-server defaults 95 10

- name: Create apm-server.yml
  template:
    src: templates/apm_server.yml.j2
    dest: /etc/apm-server/apm-server.yml

- name: Change file ownership of apm-server.yml
  file:
    path: /etc/apm-server/apm-server.yml
    owner: apm-server

- name: Create nginx conf for apm
  template:
    src: templates/nginx_apm_server.conf.j2
    dest: /etc/nginx/sites-available/apm.conf

- name: Add apm site to enabled sites
  file:
    src: /etc/nginx/sites-available/apm.conf
    dest: /etc/nginx/sites-enabled/apm.conf
    state: link

- name: Change file ownership of meta.json
  file:
    path: /var/lib/apm-server/meta.json
    owner: apm-server


- name: Change file ownership of fields.yml
  file:
    path: /etc/apm-server/fields.yml
    owner: apm-server

- name: Enabling and starting apm-server as a systemd service
  systemd:
    enabled: yes
    name: apm-server
    daemon_reload: yes
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted