---
- name: Install APM Server
  apt: name=apm-server

- name: Configure APM server to start automatically at boot
  command: update-rc.d apm-server defaults 95 10

- name: Set secret token in apm-server.yml
  command: yq w -i /etc/apm-server/apm-server.yml apm-server.secret_token {{ apm_secret_token }}

- name: Enabling Real User Monitoring
  command: yq w -i /etc/apm-server/apm-server.yml apm-server.rum.enabled true

- name: Setting allowed origins for RUM
  command: yq w -i /etc/apm-server/apm-server.yml apm-server.rum.allow_origins ['*']

- name: Create nginx conf for apm
  template:
    src: templates/nginx_apm_server.conf.j2
    dest: /etc/nginx/sites-available/apm.conf

- name: Add apm site to enabled sites
  file:
    src: /etc/nginx/sites-available/apm.conf
    dest: /etc/nginx/sites-enabled/apm.conf
    state: link

- name: Enabling and starting apm-server as a systemd service
  systemd:
    enabled: yes
    name: apm-server
    daemon_reload: yes
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted