---
- name: Download APM Server
  get_url:
    url: https://artifacts.elastic.co/downloads/apm-server/apm-server-6.6.1-amd64.deb
    dest: /tmp/apm-server-6.6.1-amd64.deb

- name: Install APM Server
  apt:
    deb: /tmp/apm-server-6.6.1-amd64.deb

- name: Set secret token in apm-server.yml
  yedit:
    src: /etc/apm-server/apm-server.yml
    key: apm-server.secret_token
    value: {{ apm_secret_token }}

- name: Set secret token in apm-server.yml
  yedit:
    src: /etc/apm-server/apm-server.yml
    key: apm-server.rum.enabled
    value: true

- name: Enabling and starting apm-server as a systemd service
  systemd:
    enabled: yes
    name: apm-server
    daemon_reload: yes
    state: started