---
- name: Download APM Server
  get_url:
    url: https://artifacts.elastic.co/downloads/apm-server/apm-server-6.6.1-amd64.deb
    dest: /tmp/apm-server-6.6.1-amd64.deb

- name: Install APM Server
  apt:
    deb: /tmp/apm-server-6.6.1-amd64.deb

- name: Set secret token in apm-server.yml
  command: yq w -i /etc/apm-server/apm-server.yml apm-server.secret_token {{ apm_secret_token }}

- name: Enabling Real User Monitoring
  command: yq w -i /etc/apm-server/apm-server.yml apm-server.rum.enabled true

- name: Enabling Real User Monitoring
  command: yq w -i /etc/apm-server/apm-server.yml apm-server.rum.allow_origins ['*']

- name: Create nginx conf for apm
  template:
    src: templates/nginx_apm_server.conf.j2
    dest: /etc/nginx/sites-available/apm.conf

- name: Add kibana site to enabled sites
  file:
    src: /etc/nginx/sites-available/apm.conf
    dest: /etc/nginx/sites-enabled/apm.conf
    state: link

- name: Enabling and starting apm-server as a systemd service
  systemd:
    enabled: yes
    name: apm-server
    daemon_reload: yes
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted